app_platform/app_platform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include('project.urls', namespace='project')),
]

app_platform/project/urls.py
from django.urls import path

from . import views

app_name = 'project'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<str:project_slug>/', views.update, name='update'),
    path('<str:project_slug>/data/', views.input_data, name='data'),
    path('<str:project_slug>/delete/', views.delete, name='delete'),
    path('<str:project_slug>/jobs', views.list_jobs, name='list_jobs'),
    path('<str:project_slug>/job/create', views.create_job, name='create_job'),
    path('<str:project_slug>/job/<int:job_id>/logs', views.job_logs, name='job_logs'),
]

app_platform/project/models.py
from multiprocessing import Process
from django.db import models
from django.conf import settings
import os.path
from django.utils.text import slugify
from .services.docker import run_app_image, setup_temp_db
from .services.nocodb import setup_nocodb_project
import psutil

class Project(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # temporary db path used by the project
    db_path = models.CharField(max_length=1024)
    # docker image name of the app 
    app_image = models.CharField(max_length=1024)

    noco_project_id = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name

    # override the save method to create a temporary db for the project
    def save(self, *args, **kwargs):
        # create the slug field from the name
        self.slug = slugify(self.name)
        # create a temporary db for the project
        if not self.db_path:
            self.db_path = os.path.join(settings.TEMP_DIR, f'{self.slug}.db')
            setup_temp_db(self.db_path, self.app_image)

        if not self.noco_project_id:
            self.noco_project_id = setup_nocodb_project(self.db_path, self.name)

        super().save(*args, **kwargs)



class Job(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # json string of the configuration
    config = models.TextField()

    # the path to the running logs
    log_path = models.CharField(max_length=1024)


    def __str__(self):
        return f"{self.project.name} - {self.created_at}"

    # override the save method to start a fire-and-foreget process to run the app
    def save(self, *args, **kwargs):
        # create a log file for the job
        if not self.log_path:
            filename = f'{self.project.slug}_{self.created_at}.log'
            filename = slugify(filename)
            self.log_path = os.path.join(settings.TEMP_DIR, filename)
        super().save(*args, **kwargs)

    def start_run(self):
        """
        Start to run the app image
        """
        config_file_name = f'{self.project.slug}_{self.created_at}.json'
        config_file_name = slugify(config_file_name)
        config_path = os.path.join(settings.TEMP_DIR, config_file_name)
        # write the config to config_path
        with open(config_path, 'w') as f:
            f.write(self.config)
        logs = run_app_image(self.project.app_image, self.project.db_path, config_path, self.log_path)
        return logs



    # return the logs of the job
    @property
    def logs(self):
        with open(self.log_path, 'r') as f:
            return f.read()

app_platform/project/forms.py
from pyexpat import model
from .models import Project
from django import forms
from .services.docker import verify_if_docker_image_exists


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'app_image']

    # validate if the docker image as specified in the form exists
    def clean_app_image(self):
        app_image = self.cleaned_data['app_image']
        is_exists = verify_if_docker_image_exists(app_image)
        if not is_exists:
            raise forms.ValidationError(f'Docker image {app_image} does not exist')
        return app_image

app_platform/project/views.py
from django.shortcuts import render, redirect
from . import models, forms
from .services.docker import get_app_config_spec
from django.conf import settings
import json
import django.forms as django_forms


def index(request):
    """
    Show a list of all projects.
    """
    projects = models.Project.objects.all()

    context = {
        'projects': projects,
    }
    return render(request, 'project/index.html', context)



def update(request, project_slug):
    """
    Update a project.
    """
    project = models.Project.objects.get(slug=project_slug)
    if request.method == 'POST':
        form = forms.ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            return redirect('project:index')

    else:
        form = forms.ProjectForm(instance=project)

    return render(request, 'project/update.html', {'form': form})



def delete(request, project_slug):
    """
    Delete a project.
    """
    pass
   

def create(request):
    """
    Create a new project.
    """
    if request.method == 'POST':
        form = forms.ProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('project:index')
    else:
        form = forms.ProjectForm()

    context = {
        'form': form,
    }

    return render(request, 'project/create.html', context)


def input_data(request, project_slug):
    """
    Show the input data for a project.
    """
    project = models.Project.objects.get(slug=project_slug)

    base_url = settings.NOCODB_URL
    nocodb_url = f"{base_url.rstrip('/')}/dashboard/#/nc/{project.noco_project_id}/auth"

    context = {
        "noco_url": nocodb_url,
        "project": project,
    }

    return render(request, 'project/data.html', context)


def list_jobs(request, project_slug):
    """
    List all jobs for a project.
    """
    project = models.Project.objects.get(slug=project_slug)
    jobs = project.job_set.all()

    context = {
        "project": project,
        "jobs": jobs
    }

    return render(request, 'project/list_jobs.html', context)


def create_job(request, project_slug):
    """
    Create a run for a project.
    """
    project = models.Project.objects.get(slug=project_slug)

    # get the config spec of the app_image
    config_spec = get_app_config_spec(project.app_image)
    config = json.loads(config_spec)

    # create a dynamic form based on the json schema as specified in config
    json_schema_type_to_field_type = {
        "string": django_forms.CharField,
        "integer": django_forms.IntegerField,
        "number": django_forms.FloatField,
        "boolean": django_forms.BooleanField,
    }

    class DynamicJobForm(django_forms.Form):

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field in config['properties']:
                field_type = json_schema_type_to_field_type[config['properties'][field]['type']]
                self.fields[field] = field_type(
                    label=field
                )


    if request.method == 'POST':
        form = DynamicJobForm(request.POST)
        if form.is_valid():
            # convert form data to json
            config = json.dumps(form.cleaned_data)
            # create a new job
            job = models.Job(
                project=project,
                config=config
            )
            job.save()

            # kickoff the container run job
            job.start_run()
            return redirect('project:list_jobs', project_slug=project_slug)

    else:
        form = DynamicJobForm()

    return render(request, 'project/create_job.html', {'form': form, 'project': project})


def job_logs(request, project_slug, job_id):
    """
    Show the logs for a job.
    """

    job = models.Job.objects.get(id=job_id)

    context = {
        "job": job,
        "project_slug": project_slug,
    }

    return render(request, 'project/job_logs.html', context)

app_platform/templates/base.html
<!-- the base html template to be extended by all app htmls -->


<html>

<head>
    {% block head %}
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>
        {% block title %}App Platform{% endblock %}
    </title>
    <!-- include bootstrap5 css from cdn -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Workflow platform</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>



</body>

</html>

app_platform/templates/project/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Create a new project
{% endblock %}

{% block content %}
<!-- render a form to create a new project -->
<form method="post">
    {{ form|crispy }}
    {% csrf_token %}

    <button type="submit" class="btn btn-primary">Create</button>
    <a type="button" class="btn"  href="{% url 'project:index' %}">Back</a>
</form>

{% endblock %}

app_platform/templates/project/create_job.html
{% extends 'base.html' %}
{% load crispy_forms_tags%}

{% block title %}
Create a run
{% endblock %}

{% block content %}
<form method="post">
    {{ form | crispy }}
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Create</button>
    <a type="button" class="btn"  href="{% url 'project:list_jobs' project.slug %}">Back</a>
</form>
{% endblock %}

app_platform/templates/project/data.html
{% extends  "base.html" %}

{% block content %}
    <div class="justify-content-end my-2">
        <!-- button to create a new project     -->
        <a type="button" class="btn btn-primary"  href="{% url 'project:index' %}">Save</a>
    </div>
    <iframe src="{{ noco_url }}" frameborder="0" width="100%" height="100%"></iframe>

{% endblock %}

app_platform/templates/project/index.html
{% extends "base.html" %}

{% block content %}
<div>
<!-- button to create a new project     -->
    <a type="button" class="btn btn-primary"  href="{% url 'project:create' %}">Create a new project</a>
</div>
<!-- show a table with all projects -->
<table class="table">
    <thead>
        <tr>
            <th>Project name</th>
            <th>Project description</th>
            <th>Project actions</th>
        </tr>
    </thead>
    <tbody>
        {% for project in projects %}
        <tr>
            <td>{{ project.name }}</td>
            <td>{{ project.description }}</td>
            <td>
                <a href="{% url 'project:update' project.slug %}">View</a>
                <a href="{% url 'project:data' project.slug %}">Data</a>
                <a href="{% url 'project:list_jobs' project.slug %}">View runs</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock %}

app_platform/templates/project/job_logs.html
{% extends 'base.html' %}

{% block content %}
<div>
    <pre>
        {{ job.logs }}
    </pre>
</div>

<a href="{% url 'project:list_jobs' project_slug %}"></a>

{% endblock %}

app_platform/templates/project/list_jobs.html
{% extends 'base.html'  %}


{% block content %}
<div>
    <a href="{% url 'project:create_job' project.slug  %}" class="btn btn-primary my-2" >Create a new run</a>
</div>


<table class="table">
    <thead>
        <tr>
            <th>Created at</th>
            <th>Log path</th>
            <th>Run actions</th>
        </tr>
    </thead>
    <tbody>
    {% for job in jobs %}
        <tr>
            <td>{{ job.created_at }}</td>
            <td>{{ job.log_path }}</td>
            <td>
                <a href="{% url 'project:job_logs'  project.slug  job.pk  %}">View log</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>

</table>

{% endblock %}

app_platform/templates/project/update.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Create a new project
{% endblock %}

{% block content %}
<!-- render a form to create a new project -->
<form method="post">
    {{ form|crispy }}
    {% csrf_token %}

    <button type="submit" class="btn btn-primary">Save</button>
    <a type="button" class="btn"  href="{% url 'project:index' %}">Back</a>
</form>

{% endblock %}